-- land_sales columns are exactly the unique CoStar CSV headers (277).
-- The export lists Sprinklers twice; Postgres cannot have two columns of that name.
-- No extra columns. All values nullable.

create table public.land_sales (
  "Property Address" text,
  "Property City" text,
  "Property State" text,
  "Property Type" text,
  "Land Area AC" numeric,
  "Land Area SF" numeric,
  "Star Rating" text,
  "Sale Price" numeric,
  "Sale Date" timestamp,
  "Sale Status" text,
  "Asking Price" numeric,
  "Price Per AC Land" numeric,
  "Price Per SF Land" numeric,
  "Sale Type" text,
  "Property Name" text,
  "Buyer (True) Company" text,
  "Buyer (True) Type" text,
  "Buyer (True) Secondary Type" text,
  "Buyer (True) Origin" text,
  "Acquisition Fund Name" text,
  "Buyers Broker Company" text,
  "Seller (True) Company" text,
  "Seller (True) Type" text,
  "Seller (True) Secondary Type" text,
  "Seller (True) Origin" text,
  "Listing Broker Company" text,
  "Hold Period" text,
  "Secondary Type" text,
  "Proposed Use" text,
  "Zoning" text,
  "Market" text,
  "Disposition Fund Name" text,
  "Submarket Name" text,
  "Location Type" text,
  "Property County" text,
  "Country" text,
  "Subcontinent" text,
  "Continent" text,
  "Property Zip Code" text,
  "Corner" text,
  "Map Code" text,
  "Actual Cap Rate" numeric,
  "Affordable Type" text,
  "Age" text,
  "All-Inclusive" text,
  "All-Suites" text,
  "Amenities" text,
  "Anchor Tenants" text,
  "Assessed Improved" numeric,
  "Assessed Land" numeric,
  "Assessed Value" numeric,
  "Assessed Year" bigint,
  "Average Rental Rate Per kW" text,
  "Avg Unit SF" text,
  "Brand" text,
  "Building Class" text,
  "Building Condition" text,
  "Building Materials" text,
  "Building Operating Expenses" text,
  "Building Park" text,
  "Building SF" text,
  "Building Tax Expenses" text,
  "Buyer (Contact) Address" text,
  "Buyer (Contact) City" text,
  "Buyer (Contact) Company" text,
  "Buyer (Contact) Contact Name" text,
  "Buyer (Contact) Phone" text,
  "Buyer (Contact) State" text,
  "Buyer (Contact) Zip Code" text,
  "Buyer (Recorded) Address" text,
  "Buyer (Recorded) City" text,
  "Buyer (Recorded) Company" text,
  "Buyer (Recorded) Contact Name" text,
  "Buyer (Recorded) Phone" text,
  "Buyer (Recorded) State" text,
  "Buyer (Recorded) Street Name" text,
  "Buyer (Recorded) Street Number" text,
  "Buyer (Recorded) Street Post-Direction" text,
  "Buyer (Recorded) Street Pre-Direction" text,
  "Buyer (Recorded) Zip Code" text,
  "Buyer (True) Address" text,
  "Buyer (True) City" text,
  "Buyer (True) Contact Name" text,
  "Buyer (True) Phone" text,
  "Buyer (True) Post-Direction" text,
  "Buyer (True) Pre-Direction" text,
  "Buyer (True) State" text,
  "Buyer (True) Street Name" text,
  "Buyer (True) Street Number" text,
  "Buyer (True) Zip Code" text,
  "Buyers Broker Address" text,
  "Buyers Broker Agent First Name" text,
  "Buyers Broker Agent Last Name" text,
  "Buyers Broker City" text,
  "Buyers Broker Phone" text,
  "Buyers Broker State" text,
  "Buyers Broker Street Name" text,
  "Buyers Broker Street Number" text,
  "Buyers Broker Street Post-Direction" text,
  "Buyers Broker Street Pre-Direction" text,
  "Buyers Broker Zip Code" text,
  "Capacity - Available kW" text,
  "Capacity - Critical IT kW" text,
  "Capacity - Total Utility kW" text,
  "Ceiling Height" text,
  "Column Spacing" text,
  "Comp ID" bigint,
  "Comps Number" text,
  "Construction Begin" text,
  "Construction Material" text,
  "Cooling Redundancy" text,
  "Coverage" text,
  "Cross Street" text,
  "Data Center Tier" text,
  "Data Center Type" text,
  "Data Hall Area SF" text,
  "Data Hall Count" text,
  "Density kW/rack" text,
  "Density kW/SF" text,
  "Description Text" text,
  "Document Number" text,
  "Down Payment" numeric,
  "Drive Ins" text,
  "Electric Utility" text,
  "Fips Code" text,
  "Fire Sprinkler" text,
  "First Trust Deed Balance" numeric,
  "First Trust Deed Lender" text,
  "First Trust Deed Payment" text,
  "First Trust Deed Terms" text,
  "Flood Risk" text,
  "Flood Zone" text,
  "Floor Area Ratio" text,
  "Frontage" text,
  "GIM" text,
  "GRM" text,
  "Gross Income" text,
  "Has Lab Space" boolean,
  "Heating" text,
  "Hotel Class" text,
  "Hotel Location Type" text,
  "Hotel Operator" text,
  "Improvement Ratio" numeric,
  "Lab Space (SF)" text,
  "Lab Space Percent Composition" text,
  "Land Improvements" text,
  "Land SF Gross" numeric,
  "Land SF Net" numeric,
  "Latitude" numeric,
  "Legal Description" text,
  "Listing Broker Address" text,
  "Listing Broker Agent First Name" text,
  "Listing Broker Agent Last Name" text,
  "Listing Broker City" text,
  "Listing Broker Phone" text,
  "Listing Broker State" text,
  "Listing Broker Street Name" text,
  "Listing Broker Street Number" text,
  "Listing Broker Street Post-Direction" text,
  "Listing Broker Street Pre-Direction" text,
  "Listing Broker Zip Code" text,
  "Loading Docks" text,
  "Longitude" numeric,
  "Lot Dimensions" text,
  "Map Page" text,
  "Map X" text,
  "Map Y" text,
  "Market Time" bigint,
  "Multi-Sale Name" text,
  "Net Income" text,
  "Non-Arms Length Reasons" text,
  "Number of 1 Bedroom Units" text,
  "Number of 2 Bedroom Units" text,
  "Number of 3 Bedroom Units" text,
  "Number of Beds" text,
  "Number of Cranes" text,
  "Number of Floors" bigint,
  "Number of Other Bedroom Units" text,
  "Number of Parking Spaces" text,
  "Number of Rooms" text,
  "Number of Studio Units" text,
  "Number of Tenants" bigint,
  "Number of Units" text,
  "Office Space" text,
  "One Bedroom Mix" text,
  "Other Mix" text,
  "Parcel Number 1 (Min)" text,
  "Parcel Number 2 (Max)" text,
  "Parent Company" text,
  "Parking Ratio" text,
  "Percent Leased" numeric,
  "Percent Office" text,
  "Portfolio City" text,
  "Portfolio County" text,
  "Portfolio Name" text,
  "Portfolio State" text,
  "Portfolio Zip" text,
  "Power" text,
  "Power Redundancy" text,
  "Power Usage Effectiveness" text,
  "Pre-Leasing" text,
  "Price Per AC Land Net" numeric,
  "Price Per Room" text,
  "Price Per SF" text,
  "Price Per SF (Net)" text,
  "Price Per SF Land Net" numeric,
  "Price Per Total kW" text,
  "Price Per Unit" text,
  "Pro Forma Cap Rate" text,
  "Property Street Name" text,
  "Property Street Number" text,
  "Property Street Post-Direction" text,
  "Property Street Pre-Direction" text,
  "PropertyID" bigint,
  "Publication Date" timestamp,
  "Rail Served" text,
  "Recording Date" timestamp,
  "Region" text,
  "Research Status" text,
  "Roof Type" text,
  "Sale Category" text,
  "Sale Condition" text,
  "Sale Price Comment" text,
  "Scale" text,
  "Second Trust Deed Balance" numeric,
  "Second Trust Deed Lender" text,
  "Second Trust Deed Payment" text,
  "Second Trust Deed Terms" text,
  "Seller (Contact) Address" text,
  "Seller (Contact) City" text,
  "Seller (Contact) Company" text,
  "Seller (Contact) Contact Name" text,
  "Seller (Contact) Phone" text,
  "Seller (Contact) State" text,
  "Seller (Contact) Zip Code" text,
  "Seller (Recorded) Address" text,
  "Seller (Recorded) City" text,
  "Seller (Recorded) Company" text,
  "Seller (Recorded) Contact Name" text,
  "Seller (Recorded) Phone" text,
  "Seller (Recorded) State" text,
  "Seller (Recorded) Street Name" text,
  "Seller (Recorded) Street Number" text,
  "Seller (Recorded) Street Post-Direction" text,
  "Seller (Recorded) Street Pre-Direction" text,
  "Seller (Recorded) Zip Code" text,
  "Seller (True) Address" text,
  "Seller (True) City" text,
  "Seller (True) Contact Name" text,
  "Seller (True) Phone" text,
  "Seller (True) Post-Direction" text,
  "Seller (True) Pre-Direction" text,
  "Seller (True) State" text,
  "Seller (True) Street Name" text,
  "Seller (True) Street Number" text,
  "Seller (True) Zip Code" text,
  "Sewer" text,
  "Size" text,
  "Sprinklers" text,
  "Stamp" text,
  "Studio Mix" text,
  "Submarket Cluster" text,
  "Submarket Code" text,
  "Tenancy" text,
  "Three Bedroom Mix" text,
  "Title Company" text,
  "Total Expense Amount" text,
  "Transaction Notes" text,
  "Transfer Tax" numeric,
  "Two Bedroom Mix" text,
  "Typical Floor (SF)" text,
  "Units Per Acre" text,
  "University" text,
  "Vacancy" text,
  "Water" text,
  "Year Built" text,
  "Year Renovated" text
);

alter table public.land_sales enable row level security;

create policy "active users can read land_sales" on public.land_sales
  for select to authenticated
  using (public.current_user_active());
create policy "editors can insert land_sales" on public.land_sales
  for insert to authenticated
  with check (public.current_user_active() and public.current_user_role() in ('Editor','Admin'));
create policy "editors can update land_sales" on public.land_sales
  for update to authenticated
  using (public.current_user_active() and public.current_user_role() in ('Editor','Admin'))
  with check (public.current_user_active() and public.current_user_role() in ('Editor','Admin'));
create policy "admins can delete land_sales" on public.land_sales
  for delete to authenticated
  using (public.current_user_active() and public.current_user_role() = 'Admin');

grant select, insert, update, delete on public.land_sales to authenticated;

notify pgrst, 'reload schema';
